#ifndef DEVICE_CONFIG_H
#define DEVICE_CONFIG_H

#define BAUDRATE 115200
#define BITS_PER_BYTE 10
#define BIT_TIME_US (1000000 / BAUDRATE)
#define CHAR_TIME_US (BIT_TIME_US * BITS_PER_BYTE)
#define DEVICE_NAME "Virtual Keyboard 115200"
#define VENDOR_ID 0x1234
#define PRODUCT_ID 0x5678
#define DEVICE_VERSION 0x0001
#define KEY_PRESS_DELAY CHAR_TIME_US
#define KEY_RELEASE_DELAY CHAR_TIME_US
#define INTER_KEY_DELAY (CHAR_TIME_US * 2)

#endif